name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  appinspect-job:
    runs-on: ubuntu-latest
    steps:
      - uses: splunk/appinspect-api-action@v3.0
        with:
          username: ${{ secrets.SPL_COM_USER }}
          password: ${{ secrets.SPL_COM_PASSWORD }}
          app_path: build/package/
          included_tags: "cloud,self-service"
          excluded_tags: "offensive"
