name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  appinspect-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Create build dir
        run: mkdir build/package/
      - name: Compress archive
        run : tar -czvf build/package/TA-lw.spl * --transform='s,^,/TA-lw/,'
      - name: Test Archive
        run: tar -txzvf build/package/TA-lw.spl
      - uses: splunk/appinspect-api-action@v3.0
        with:
          username: ${{ secrets.SPL_COM_USER }}
          password: ${{ secrets.SPL_COM_PASSWORD }}
          app_path: build/package/
          included_tags: "cloud,self-service"
          excluded_tags: "offensive"
